name: Deploy Pages (publish src)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5

      - name: Prepare artifact from src/
        run: |
          rm -rf _site
          mkdir -p _site
          cp -R src/* _site/
          touch _site/.nojekyll
          if [ ! -f _site/index.html ]; then
            printf '%s' '<!doctype html><html><head><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=pages/fromEmpresas/index.html"><script>location.replace("pages/fromEmpresas/index.html");</script><title>Redirecionando…</title></head><body></body></html>' > _site/index.html
          fi

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - id: deployment
        uses: actions/deploy-pages@v4